image: node:latest

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
   # - npm link @angular/cli

stages:
  #  - test
    - production


# unit-test:
   # stage: test
   # image: trion/ng-cli-karma:latest
   # script:
     #   - npm install 
    #    - ng test 
  #  only:
 #       - master

production:
    type: deploy
    stage: production
    image: ruby:latest
    script:
        - npm install
        - echo "ACCOUNT_SID=$ACCOUNT_SID" >> .env
        - echo "AUTH_TOKEN=$AUTH_TOKEN" >> .env
        - echo "API_KEY=$API_KEY" >> .env
        - echo "API_SECRET=$API_SECRET" >> .env
        - echo "PHONE_NUMBER=$PHONE_NUMBER" >> .env
        - echo "sengrid_api=$sengrid_api" >> .env
        - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY --skip_cleanup
    only:
        - master