image: node:latest

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
   # - npm link @angular/cli

stages:
  #  - test
    - production


# unit-test:
   # stage: test
   # image: trion/ng-cli-karma:latest
   # script:
     #   - npm install 
    #    - ng test 
  #  only:
 #       - master

production:
    type: deploy
    stage: production
    script:
        - echo -e "ACCOUNT_SID=${ACCOUNT_SID} \n" >> .env
        - echo -e "AUTH_TOKEN =${AUTH_TOKEN} \n" >> .env
        - echo -e "API_KEY=${API_KEY} \n" >> .env
        - echo -e "API_SECRET=${API_SECRET} \n" >> .env
        - echo -e "PHONE_NUMBER =${PHONE_NUMBER} \n" >> .env
        - echo -e "sengrid_api =${sengrid_api} \n" >> .env
        - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
    only:
        - master